version: 2
updates:
  # Enable version updates for NuGet
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "willmortimer"
    assignees:
      - "willmortimer"
    commit-message:
      prefix: "deps"
      include: "scope" 